import type { Metadata } from "next";
import "./globals.css";

import Header from "@/components/Header/Header";
import StoreProvider from "./StoreProvider";
import { ToastProvider } from "./ToastProvider";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "1fyKzbkEU1c_SAmHxDUgnnZVvJNskNb7ZBBlNTNNLhU",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en">
        <body className="min-h-screen flex flex-col">
          <header className="fixed left-0 right-0 top-0 bg-[#101319] z-10 flex justify-between border-b px-3 md:px-6 py-4 items-center gap-3 border-[#272c3480]">
            <Header text="SkillPath" subText="Dev" isDisplay={false} />
          </header>
          <StoreProvider>
            <main className="grow overflow-y-auto">{children}</main>
            <ToastProvider />
          </StoreProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
