import type { Metadata } from "next";
import "./globals.css";

import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <div className="fixed left-0 right-0 top-0 bg-[#101319] z-10">
          <Header />
        </div>
        <div className="grow overflow-y-auto">{children}</div>
      </body>
    </html>
  );
}
